//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuon
    {
        public ChiTietPhieuMuon()
        {
            this.Phats = new HashSet<Phat>();
        }
    
        public int MaChiTietPhieuMuon { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> MaPhieuMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<int> LanMuon { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual ICollection<Phat> Phats { get; set; }
    }
}
