//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int MaChiTietDonHang { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> Stt { get; set; }
        public string TenSach { get; set; }
        public string NhanDeChinh { get; set; }
        public string NhanDePhu { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> SoCuon { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string KichThuoc { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<System.DateTime> NgayGiaoThucTe { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> NhaXuatBan { get; set; }
        public Nullable<int> Cuon { get; set; }
        public Nullable<int> Tap { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual NhaXuatBan NhaXuatBan1 { get; set; }
    }
}
