//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public DanhMuc()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
