//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GopY
    {
        public int MaGopY { get; set; }
        public string NguoiGopY { get; set; }
        public Nullable<System.DateTime> TimeGopY { get; set; }
        public string Email { get; set; }
        public Nullable<int> NguoiDungGopY { get; set; }
        public string NoiDungGopY { get; set; }
        public Nullable<bool> DaXem { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
