//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.Gopies = new HashSet<GopY>();
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int MaNguoiDung { get; set; }
        public string HoTen { get; set; }
        public string SoCMND { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MSSV { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string LoaiND { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
    
        public virtual ICollection<GopY> Gopies { get; set; }
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
