//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaXuatBan
    {
        public NhaXuatBan()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaNhaXuatBan { get; set; }
        public string TenNhaXuatBan { get; set; }
        public string DiaChi { get; set; }
        public string SoTaiKhoan { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
