//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phat
    {
        public int MaPhat { get; set; }
        public Nullable<int> ChiTietPhieuMuon { get; set; }
        public Nullable<int> QuyDinhPhat { get; set; }
        public Nullable<System.DateTime> NgayNopPhat { get; set; }
        public Nullable<double> SoTienNop { get; set; }
        public Nullable<int> NguoiThu { get; set; }
    
        public virtual ChiTietPhieuMuon ChiTietPhieuMuon1 { get; set; }
        public virtual QuyDinhPhat QuyDinhPhat1 { get; set; }
    }
}
