//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        public PhieuMuon()
        {
            this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();
        }
    
        public int MaPhieuMuon { get; set; }
        public Nullable<int> NhanVien { get; set; }
        public Nullable<int> NguoiMuon { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> SoLuongSach { get; set; }
        public Nullable<bool> TinhTrangMuon { get; set; }
    
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
