//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinhPhat
    {
        public QuyDinhPhat()
        {
            this.Phats = new HashSet<Phat>();
        }
    
        public int MaQuyDinhPhat { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> SoTien { get; set; }
    
        public virtual ICollection<Phat> Phats { get; set; }
    }
}
