//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string NhanDeChinh { get; set; }
        public string NhanDePhu { get; set; }
        public Nullable<System.DateTime> NamXuatBan { get; set; }
        public string TinhTrangSach { get; set; }
        public Nullable<bool> TinhTrangMuon { get; set; }
        public Nullable<double> GiaSach { get; set; }
        public string KichThuoc { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<int> Cuon { get; set; }
        public Nullable<int> Tap { get; set; }
        public string XemTruoc { get; set; }
        public string TomTat { get; set; }
        public Nullable<int> TacGia { get; set; }
        public Nullable<int> NhaXuatBan { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual NhaXuatBan NhaXuatBan1 { get; set; }
        public virtual TacGia TacGia1 { get; set; }
    }
}
