//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_N8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public TacGia()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaTacGia { get; set; }
        public string TenTacGia { get; set; }
        public string QuocTich { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public string TenVietTat { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
